version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm i yarn
      - run: yarn
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - setup_remote_docker
      - run: |
          git clone https://github.com/makerdao/staxx.git
          cd staxx
          make run-dev
          cd ..
          yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
