version: 2
jobs:
  test:
    machine: true
    working_directory: ~/testchain-client
    steps:
      - checkout
      - run:
          name: update Node.js version
          command: |
            set +e
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v11.15.0
            nvm alias default v11.15.0
            # persistance for the new version
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"" >> $BASH_ENV
      - run:
          name: spin up staxx environment
          command: |
            #ssh-keyscan github.com >> ~/.ssh/known_hosts
            #echo "${DEPLOYMENT_KEY}" | base64 -d > "~/.ssh/id_rsa"
            git clone https://github.com/b-pmcg/staxx.git
            cd staxx
            git checkout debug-testchain-client
            make run-dev
      - run:
          name: run tests
          command: |
            npm i yarn -g
            yarn
            yarn test
      - run:
          name: Notifiation Failed
          command: bash .circleci/notify "failed"
          when: on_fail
      - run:
          name: Notification Sucess
          command: bash ./circleci/notify "success"
          when: on_success

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
