version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm i yarn
      - run: yarn
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - setup_remote_docker
      - run: |
          git clone https://github.com/b-pmcg/staxx.git
          cd staxx
          git checkout debug-testchain-client
          sudo docker-compose -f ./docker-compose-dev.yml up -d
          cd ..
          ls -al
          yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
